name: Build and Sign macOS
on:
  push:
    tags:
      - '*'
    branches:
      - main
jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: xcodebuild
        
      - name: Show Files
        run: find .

      - name: Upload Unsigned app
        uses: actions/upload-artifact@v1
        with:
          name: CGMBar-unsigned
          path: build/Release/CGMBar.app
           
      - name: Read certificate
        id: write_file
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'certificate.p12'
          encodedString: ${{ secrets.MACOS_CERTIFICATE }}

      - name: Codesign executable
        env: 
          CERTIFICATE_P12: ${{ steps.write_file.outputs.filePath }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
        run: |
          echo $CERTIFICATE_P12
          cp $CERTIFICATE_P12 ./certificate.p12
          security create-keychain -p $MACOS_CERTIFICATE_PWD build.keychain security default-keychain -s build.keychain
          security unlock-keychain -p $MACOS_CERTIFICATE_PWD build.keychain
          security import certificate.p12 -k build.keychain -P $MACOS_CERTIFICATE_PWD -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k $MACOS_CERTIFICATE_PWD build.keychain
          /usr/bin/codesign --force -s $MACOS_CERTIFICATE_ID ./build/Release/CGMBar.app -v

      - name: Upload Signed app
        uses: actions/upload-artifact@v1
        with:
          name: CGMBar-signed
          path: build/Release/CGMBar.app
