name: Build and Sign macOS
on:
  push:
    tags:
      - '*'
    branches:
      - main
jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: xcodebuild
        
      - name: Show Files
        run: find .
        
      - name: Copy unsigned app
        run: |
          mkdir $RUNNER_TEMP/unsigned_app
          cp -r build/Release/CGMBar.app $RUNNER_TEMP/unsigned_app/

      - name: Upload Unsigned app
        uses: actions/upload-artifact@v2
        with:
          name: CGMBar-unsigned
          path: ${{ runner.temp }}/unsigned_app/
          
      - name: Install certificate
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.MACOS_CERTIFICATE }}
          P12_PASSWORD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
          KEYCHAIN_PASSWORD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
          CERTIFICATE_ID: ${{ secrets.MACOS_CERTIFICATE_ID }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH

          # create temporary keychain
          security create-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P $P12_PASSWORD -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH
          
          # set-key-partition-list and codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k $MACOS_CERTIFICATE_PWD $KEYCHAIN_PATH
          /usr/bin/codesign --force -s $CERTIFICATE_ID ./build/Release/CGMBar.app -v


      - name: Copy signed app
        run: |
          mkdir $RUNNER_TEMP/signed_app
          cp -r build/Release/CGMBar.app $RUNNER_TEMP/signed_app/

      - name: Upload Signed app
        uses: actions/upload-artifact@v2
        with:
          name: CGMBar-signed
          path: ${{ runner.temp }}/signed_app/
